# Generated by Django 3.2.11 on 2022-02-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(max_length=1000, null=True, upload_to='media/pictures'),
        ),
    ]
